from .activityDetection import automaticallyFetchActivity_Cookie
from .activityDetection import get_activityDetails_Query
from .activityDetection import get_activityQuery_Query
from .activityDetection import get_activityQuery_Get
from .activityDetection import get_Activity_Cookie
from .activity_applyAndcancel import apply_activity
from .activity_applyAndcancel import activity_cancel


